workbench_moderation.moderation_state.*:
  type: config_entity
  label: 'Moderation state config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    published:
      type: boolean
      label: 'Is published'
    default_revision:
      type: boolean
      label: 'Is default revision'
    uuid:
      type: string

node.type.*.third_party.workbench_moderation:
  type: mapping
  label: 'Enable moderation states for this node type'
  mapping:
    enabled:
      type: boolean
      label: 'Moderation states enabled'
    allowed_moderation_states:
      type: sequence
      sequence:
        type: string
        label: 'Moderation state'
    default_moderation_state:
      type: string
      label: 'Moderation state for new content'

block_content.type.*.third_party.workbench_moderation:
  type: mapping
  label: 'Enable moderation states for this block content type'
  mapping:
    enabled:
      type: boolean
      label: 'Moderation states enabled'
    allowed_moderation_states:
      type: sequence
      sequence:
        type: string
        label: 'Moderation state'
    default_moderation_state:
      type: string
      label: 'Moderation state for new block content'

views.filter.latest_revision:
  type: views_filter
  label: 'Latest revision'
  type: mapping
  mapping:
    value:
      type: string
      label: 'Value'
