media_entity_twitter.settings:
  type: config_object
  label: 'Media entity Twitter settings'
  mapping:
    local_images:
      type: string
      label: 'Base folder for thumbnails'

media_entity.bundle.type.twitter:
  type: mapping
  label: 'Twitter type configuration'
  mapping:
    source_field:
      type: string
      label: 'Field with embed code/URL'
    use_twitter_api:
      type: boolean
      label: 'Whether to use twitter api or not'
    consumer_key:
      type: string
      label: 'Field with Consumer key'
    consumer_secret:
      type: string
      label: 'Field with Consumer secret'
    oauth_access_token:
      type: string
      label: 'Field with Oauth access token'
    oauth_access_token_secret:
      type: string
      label: 'Field with Oauth access token secret'
    generate_thumbnails:
      type: boolean
      label: 'Enable automatic thumbnail generation'
